/**
 * Regenerate `src/corpus/products.ts` from our consumer's `flexCatalogMappings` reference fixture.
 *
 *   bun scripts/corpus.ts <path to flexCatalogMappings.json>
 *   <export the consumer app's flexCatalogMappings fixture> | bun scripts/corpus.ts -
 *
 * No Flex sandbox credentials exist to `corpus pull` `GET /v1/products`, so the corpus is the
 * product side of every mapping row: the Flex product id, the client reference and the consumer's
 * correlation metadata the catalog validation compares, the eligibility and visit type the
 * mapping recorded from Flex. Every product is active and test-mode (the sandbox), so running
 * our catalog validation over the corpus reproduces each mapping row's own `active` flag.
 */
import { writeFile } from "node:fs/promises"
import { join } from "node:path"

type Row = {
  purpose: string
  merchantProductId: string
  flexProductId: string
  eligibility: string
  visitType: string | null
  metadata: { flex_client_reference_id?: string }
  createdAt: string
}

const source = process.argv[2]
if (!source) {
  console.error("usage: bun scripts/corpus.ts <flexCatalogMappings.json | ->")
  process.exit(2)
}
const text =
  source === "-" ? await new Response(Bun.stdin.stream()).text() : await Bun.file(source).text()
const fixture = JSON.parse(text) as { table: string; rows: Row[] }
if (fixture.table !== "flexCatalogMappings") throw new Error(`not a flexCatalogMappings fixture`)

const byId = new Map<string, Row>()
for (const row of fixture.rows) {
  const reference = row.metadata.flex_client_reference_id
  if (!reference) throw new Error(`${row.flexProductId} has no flex_client_reference_id`)
  const existing = byId.get(row.flexProductId)
  if (existing && existing.merchantProductId !== row.merchantProductId) {
    throw new Error(`${row.flexProductId} maps to two merchant products`)
  }
  byId.set(row.flexProductId, row)
}
const rows = [...byId.values()].sort((a, b) => a.flexProductId.localeCompare(b.flexProductId))
const tuples = rows.map((row) =>
  JSON.stringify([
    row.flexProductId,
    row.purpose,
    row.merchantProductId,
    row.eligibility,
    row.visitType,
    row.metadata.flex_client_reference_id,
    row.createdAt,
  ]),
)

const out = `// Generated by scripts/corpus.ts from the consumer's flexCatalogMappings fixture. Do not edit.
// Source: the consumer app's flexCatalogMappings reference-data fixture
// (${fixture.rows.length} mapping rows, ${rows.length} distinct Flex products).

/** [product_id, purpose, merchant product id, eligibility, visit_type, client_reference_id, created_at] */
export type CorpusRow = readonly [string, string, string, string, string | null, string, string]

export const CORPUS_ROWS: readonly CorpusRow[] = [
${tuples.map((t) => `  ${t},`).join("\n")}
]
`
await writeFile(join(import.meta.dir, "..", "src", "corpus", "products.ts"), out)
console.log(`wrote ${rows.length} products`)
