import type { Scenario } from "../harness/scenario.js"

const form = "application/x-www-form-urlencoded"
const json = "application/json"

export const adminScenarios: Scenario[] = [
  {
    name: "admin: project clients and metadata",
    steps: [
      {
        name: "a non-admin client may not use the admin API",
        method: "GET",
        path: (v) => `/admin/projects/${v.projectId}`,
      },
      {
        method: "POST",
        path: (v) => `/admin/projects/${v.projectId}/client`,
        contentType: json,
        body: { name: "x" },
      },
      { method: "GET", path: (v) => `/admin/projects/${v.projectId}`, auth: "super" },
      {
        method: "POST",
        path: (v) => `/admin/projects/${v.projectId}/client`,
        auth: "super",
        contentType: json,
        body: {},
      },
      {
        method: "POST",
        path: (v) => `/admin/projects/${v.projectId}/client`,
        auth: "super",
        contentType: json,
        body: { name: "Second client", description: "made in a scenario" },
        save: { client2: (b) => b?.id, secret2: (b) => b?.secret },
      },
      {
        name: "the new client can sign in",
        method: "POST",
        path: "/oauth2/token",
        auth: "none",
        contentType: form,
        raw: (v) =>
          `grant_type=client_credentials&client_id=${v.client2}&client_secret=${v.secret2}`,
      },
      { method: "GET", path: "/admin/projects/nope/whatever", auth: "super" },
    ],
  },
  {
    name: "admin: invite validation",
    steps: [
      {
        method: "POST",
        path: (v) => `/admin/projects/${v.projectId}/invite`,
        auth: "super",
        contentType: json,
        body: {},
      },
      {
        method: "POST",
        path: (v) => `/admin/projects/${v.projectId}/invite`,
        auth: "super",
        contentType: json,
        body: {
          resourceType: "Organization",
          firstName: "A",
          lastName: "B",
          email: "not-an-email",
        },
      },
      {
        method: "POST",
        path: (v) => `/admin/projects/${v.projectId}/invite`,
        auth: "super",
        contentType: json,
        body: {
          resourceType: "Practitioner",
          firstName: "A",
          lastName: "B",
          email: "a@example.com",
          password: "short",
        },
      },
      {
        method: "POST",
        path: (v) => `/admin/projects/${v.projectId}/invite`,
        auth: "super",
        contentType: json,
        body: { resourceType: "RelatedPerson", firstName: "A", lastName: "B", externalId: "rp-1" },
      },
    ],
  },
  {
    name: "admin: invite, sign in as the invited practitioner, refresh",
    steps: [
      {
        method: "POST",
        path: (v) => `/admin/projects/${v.projectId}/invite`,
        auth: "super",
        contentType: json,
        body: {
          resourceType: "Practitioner",
          firstName: "Grace",
          lastName: "Hopper",
          email: "Grace.Hopper@Example.org",
          password: "cobol-rules-1959",
          scope: "project",
          admin: true,
          sendEmail: false,
        },
        save: { membership: (b) => b?.id, profile: (b) => b?.profile?.reference?.split("/")[1] },
      },
      {
        name: "inviting the same email again is a conflict",
        method: "POST",
        path: (v) => `/admin/projects/${v.projectId}/invite`,
        auth: "super",
        contentType: json,
        body: {
          resourceType: "Practitioner",
          firstName: "Grace",
          lastName: "Hopper",
          email: "grace.hopper@example.org",
          scope: "project",
          sendEmail: false,
        },
      },
      { method: "GET", path: (v) => `/fhir/R4/Practitioner/${v.profile}` },
      {
        method: "POST",
        path: "/auth/login",
        auth: "none",
        contentType: json,
        body: (v) => ({
          email: "grace.hopper@example.org",
          password: "cobol-rules-1959",
          projectId: v.projectId,
          scope: "openid offline_access",
          codeChallenge: "grace-challenge",
          codeChallengeMethod: "plain",
        }),
        save: { code: (b) => b?.code },
      },
      {
        method: "POST",
        path: "/oauth2/token",
        auth: "none",
        contentType: form,
        raw: (v) => `grant_type=authorization_code&code=${v.code}&code_verifier=grace-challenge`,
        save: { access: (b) => b?.access_token, refresh: (b) => b?.refresh_token },
      },
      {
        method: "GET",
        path: "/auth/me",
        auth: "none",
        headers: (v) => ({ authorization: `Bearer ${v.access}` }),
      },
      {
        method: "GET",
        path: "/oauth2/userinfo",
        auth: "none",
        headers: (v) => ({ authorization: `Bearer ${v.access}` }),
      },
      {
        method: "POST",
        path: "/fhir/R4/Patient",
        auth: "none",
        headers: (v) => ({ authorization: `Bearer ${v.access}` }),
        body: { resourceType: "Patient", name: [{ family: "Authored" }] },
      },
      {
        name: "the practitioner authors what it writes",
        method: "GET",
        path: "/fhir/R4/Patient?name=authored",
        auth: "none",
        headers: (v) => ({ authorization: `Bearer ${v.access}`, "x-medplum": "extended" }),
      },
      {
        method: "POST",
        path: "/oauth2/token",
        auth: "none",
        contentType: form,
        raw: (v) => `grant_type=refresh_token&refresh_token=${v.refresh}`,
        save: { access2: (b) => b?.access_token, refresh2: (b) => b?.refresh_token },
      },
      {
        name: "the old refresh token was rotated out",
        method: "POST",
        path: "/oauth2/token",
        auth: "none",
        contentType: form,
        raw: (v) => `grant_type=refresh_token&refresh_token=${v.refresh}`,
      },
      {
        name: "project admin reads its project",
        method: "GET",
        path: (v) => `/admin/projects/${v.projectId}`,
        auth: "none",
        headers: (v) => ({ authorization: `Bearer ${v.access2}` }),
      },
      {
        method: "GET",
        path: (v) => `/admin/projects/${v.projectId}/members/${v.membership}`,
        auth: "none",
        headers: (v) => ({ authorization: `Bearer ${v.access2}` }),
      },
      {
        name: "project admin searches memberships",
        method: "GET",
        path: "/fhir/R4/ProjectMembership",
        auth: "none",
        headers: (v) => ({ authorization: `Bearer ${v.access2}` }),
      },
      {
        name: "a plain client may not search memberships",
        method: "GET",
        path: "/fhir/R4/ProjectMembership",
      },
      {
        name: "nor read the Project",
        method: "GET",
        path: (v) => `/fhir/R4/Project/${v.projectId}`,
      },
      {
        method: "POST",
        path: "/oauth2/logout",
        auth: "none",
        headers: (v) => ({ authorization: `Bearer ${v.access2}` }),
      },
      {
        method: "GET",
        path: "/auth/me",
        auth: "none",
        headers: (v) => ({ authorization: `Bearer ${v.access2}` }),
      },
    ],
  },
  {
    name: "admin: invite a patient, then remove the member",
    steps: [
      {
        method: "POST",
        path: (v) => `/admin/projects/${v.projectId}/invite`,
        auth: "super",
        contentType: json,
        body: {
          resourceType: "Patient",
          firstName: "Pat",
          lastName: "Portal",
          email: "pat.portal@example.org",
          sendEmail: false,
        },
        save: { membership: (b) => b?.id, patient: (b) => b?.profile?.reference?.split("/")[1] },
      },
      { method: "GET", path: (v) => `/fhir/R4/Patient/${v.patient}` },
      { method: "GET", path: "/fhir/R4/Patient?email=pat.portal@example.org" },
      {
        method: "GET",
        path: (v) => `/admin/projects/${v.projectId}/members/${v.membership}`,
        auth: "super",
      },
      {
        method: "DELETE",
        path: (v) => `/admin/projects/${v.projectId}/members/${v.membership}`,
        auth: "super",
      },
    ],
  },
]
