import type { Scenario, Step } from "../harness/scenario.js"

const id = (body: { id?: string }) => body?.id

const create = (resource: Record<string, unknown>, save?: string): Step => ({
  method: "POST",
  path: `/fhir/R4/${resource.resourceType as string}`,
  body: resource,
  ...(save ? { save: { [save]: id } } : {}),
})

const search = (query: string | ((v: Record<string, string>) => string), name?: string): Step => ({
  method: "GET",
  path: typeof query === "string" ? `/fhir/R4/${query}` : (v) => `/fhir/R4/${query(v)}`,
  ...(name ? { name } : {}),
})

/** A small, varied population: names, identifiers, telecoms, addresses, dates, tags. */
const people: Step[] = [
  create(
    {
      resourceType: "Patient",
      identifier: [
        { system: "https://example.org/mrn", value: "MRN-1" },
        { system: "https://example.org/ssn", value: "111-22-3333" },
      ],
      active: true,
      name: [
        { use: "official", given: ["Ada", "King"], family: "Lovelace" },
        { use: "nickname", given: ["Countess"] },
      ],
      telecom: [
        { system: "email", value: "Ada@Example.org" },
        { system: "phone", value: "+1 555 0100", use: "home" },
      ],
      gender: "female",
      birthDate: "1815-12-10",
      address: [
        {
          line: ["12 St James's Square"],
          city: "London",
          state: "LND",
          postalCode: "SW1Y 4JH",
          country: "UK",
          use: "home",
        },
      ],
      meta: {
        tag: [{ system: "https://example.org/tags", code: "vip" }],
        profile: ["http://example.org/profiles/special"],
      },
    },
    "ada",
  ),
  create(
    {
      resourceType: "Patient",
      identifier: [{ system: "https://example.org/mrn", value: "MRN-2" }],
      active: false,
      name: [{ given: ["Charles"], family: "Babbage" }],
      telecom: [{ system: "email", value: "charles@example.org" }],
      gender: "male",
      birthDate: "1791-12-26",
      deceasedDateTime: "1871-10-18T12:00:00Z",
      address: [{ city: "Teignmouth", country: "UK" }],
    },
    "charles",
  ),
  create(
    {
      resourceType: "Patient",
      identifier: [{ value: "NO-SYSTEM-1" }],
      name: [{ given: ["Grace", "Brewster"], family: "Hopper", text: "Rear Admiral Grace Hopper" }],
      gender: "female",
      birthDate: "1906-12-09",
      address: [{ city: "New York", state: "NY", postalCode: "10001", country: "USA" }],
      meta: { tag: [{ system: "https://example.org/tags", code: "navy" }] },
    },
    "grace",
  ),
  create(
    {
      resourceType: "Patient",
      name: [
        { given: ["Alan"], family: "Turing" },
        { given: ["Alan", "Mathison"], family: "Turing", use: "official" },
      ],
      gender: "male",
      birthDate: "1912-06-23",
      multipleBirthBoolean: false,
      address: [
        { city: "London", country: "UK" },
        { city: "Wilmslow", country: "UK" },
      ],
    },
    "alan",
  ),
  create({ resourceType: "Patient", name: [{ family: "Émile-Zola" }], birthDate: "1840" }, "emile"),
  create({ resourceType: "Patient" }, "empty"),
]

const clinical: Step[] = [
  create(
    {
      resourceType: "Organization",
      name: "Analytical Engines Ltd",
      identifier: [{ system: "https://example.org/org", value: "AE" }],
    },
    "org",
  ),
  {
    method: "POST",
    path: "/fhir/R4/Practitioner",
    body: {
      resourceType: "Practitioner",
      name: [{ given: ["Mary"], family: "Somerville", prefix: ["Dr"] }],
      gender: "female",
    },
    save: { mary: id },
  },
  {
    method: "POST",
    path: "/fhir/R4/Observation",
    body: (v) => ({
      resourceType: "Observation",
      status: "final",
      category: [
        {
          coding: [
            {
              system: "http://terminology.hl7.org/CodeSystem/observation-category",
              code: "vital-signs",
            },
          ],
        },
      ],
      code: {
        coding: [{ system: "http://loinc.org", code: "8867-4", display: "Heart rate" }],
        text: "Heart rate",
      },
      subject: { reference: `Patient/${v.ada}` },
      performer: [{ reference: `Practitioner/${v.mary}` }],
      effectiveDateTime: "2024-03-01T10:00:00Z",
      valueQuantity: {
        value: 72,
        unit: "beats/minute",
        system: "http://unitsofmeasure.org",
        code: "/min",
      },
    }),
    save: { hr1: id },
  },
  {
    method: "POST",
    path: "/fhir/R4/Observation",
    body: (v) => ({
      resourceType: "Observation",
      status: "preliminary",
      code: { coding: [{ system: "http://loinc.org", code: "8867-4" }] },
      subject: { reference: `Patient/${v.charles}` },
      effectiveDateTime: "2024-03-05",
      valueQuantity: { value: 110, unit: "beats/minute" },
    }),
    save: { hr2: id },
  },
  {
    method: "POST",
    path: "/fhir/R4/Observation",
    body: (v) => ({
      resourceType: "Observation",
      status: "final",
      code: { coding: [{ system: "http://loinc.org", code: "29463-7", display: "Body weight" }] },
      subject: { reference: `Patient/${v.ada}` },
      effectivePeriod: { start: "2024-01-01T00:00:00Z", end: "2024-01-31T23:59:59Z" },
      valueQuantity: { value: 60.5, unit: "kg" },
      interpretation: [{ text: "Normal weight" }],
    }),
    save: { weight: id },
  },
  {
    method: "POST",
    path: "/fhir/R4/Encounter",
    body: (v) => ({
      resourceType: "Encounter",
      status: "finished",
      class: { system: "http://terminology.hl7.org/CodeSystem/v3-ActCode", code: "AMB" },
      subject: { reference: `Patient/${v.ada}` },
      participant: [{ individual: { reference: `Practitioner/${v.mary}` } }],
      serviceProvider: { reference: `Organization/${v.org}` },
      period: { start: "2024-03-01T09:00:00Z", end: "2024-03-01T10:30:00Z" },
    }),
    save: { encounter: id },
  },
  {
    method: "POST",
    path: "/fhir/R4/Condition",
    body: (v) => ({
      resourceType: "Condition",
      clinicalStatus: {
        coding: [
          { system: "http://terminology.hl7.org/CodeSystem/condition-clinical", code: "active" },
        ],
      },
      code: {
        coding: [{ system: "http://snomed.info/sct", code: "38341003", display: "Hypertension" }],
      },
      subject: { reference: `Patient/${v.ada}` },
      encounter: { reference: `Encounter/${v.encounter}` },
      onsetDateTime: "2020-05-05",
    }),
    save: { condition: id },
  },
]

export const searchScenarios: Scenario[] = [
  {
    name: "search: strings, names and addresses",
    steps: [
      ...people,
      search("Patient"),
      search("Patient?name=ada"),
      search("Patient?name=Ada%20Love"),
      search("Patient?name=love"),
      search("Patient?name=ace"),
      search("Patient?name=ada,grace"),
      search("Patient?name:exact=Ada%20King%20Lovelace"),
      search("Patient?name:contains=ove"),
      search("Patient?name=admiral"),
      search("Patient?name=zola"),
      search("Patient?name=emile-zola"),
      search("Patient?family=turing"),
      search("Patient?family:exact=Turing"),
      search("Patient?family:exact=turing"),
      search("Patient?given=alan"),
      search("Patient?given=mathison"),
      search("Patient?given:contains=race"),
      search("Patient?family:missing=true"),
      search("Patient?family:missing=false"),
      search("Patient?name:not=ada"),
      search("Patient?address=london"),
      search("Patient?address-city=london"),
      search("Patient?address-city:exact=London"),
      search("Patient?address-city:contains=ondo"),
      search("Patient?address-country=uk"),
      search("Patient?address-postalcode=sw1y"),
      search("Patient?address-state=ny"),
      search("Patient?address-use=home"),
      search("Patient?phonetic=lovelace"),
    ],
  },
  {
    name: "search: tokens, identifiers, telecom, booleans",
    steps: [
      ...people,
      search("Patient?identifier=MRN-1"),
      search("Patient?identifier=https://example.org/mrn|MRN-2"),
      search("Patient?identifier=https://example.org/mrn|"),
      search("Patient?identifier=|NO-SYSTEM-1"),
      search("Patient?identifier=|MRN-1"),
      search("Patient?identifier=mrn-1"),
      search("Patient?identifier:not=MRN-1"),
      search("Patient?identifier:missing=true"),
      search("Patient?identifier:text=mrn"),
      search("Patient?identifier:contains=RN"),
      search("Patient?identifier:missing=maybe"),
      search("Patient?identifier:above=MRN-1"),
      search("Patient?gender=female"),
      search("Patient?gender=FEMALE"),
      search("Patient?gender=female,male"),
      search("Patient?gender:not=female"),
      search("Patient?gender:missing=true"),
      search("Patient?active=true"),
      search("Patient?active=false"),
      search("Patient?active:not=true"),
      search("Patient?active=yes"),
      search("Patient?active:missing=true"),
      search("Patient?email=ada@example.org"),
      search("Patient?email=ADA@EXAMPLE.ORG"),
      search("Patient?email:contains=example"),
      search("Patient?telecom=phone|+1%20555%200100"),
      search("Patient?phone=+1%20555%200100"),
      search("Patient?_tag=vip"),
      search("Patient?_tag=https://example.org/tags|navy"),
      search("Patient?_tag:not=vip"),
      search("Patient?_profile=http://example.org/profiles/special"),
      search("Patient?_security:missing=true"),
      search("Patient?deceased=true"),
    ],
  },
  {
    name: "search: dates and date-times",
    steps: [
      ...people,
      search("Patient?birthdate=1815-12-10"),
      search("Patient?birthdate=gt1900-01-01"),
      search("Patient?birthdate=ge1906-12-09"),
      search("Patient?birthdate=lt1800-01-01"),
      search("Patient?birthdate=le1815-12-10"),
      search("Patient?birthdate=ne1815-12-10"),
      search("Patient?birthdate=sa1900-01-01"),
      search("Patient?birthdate=eb1900-01-01"),
      search("Patient?birthdate=ge1800-01-01&birthdate=le1900-01-01"),
      search("Patient?birthdate=1815"),
      search("Patient?birthdate=1815-12"),
      search("Patient?birthdate=1815-12-10T00:00:00Z"),
      search("Patient?birthdate=ap1815-12-10"),
      search("Patient?birthdate=bogus"),
      search("Patient?birthdate:missing=true"),
      search("Patient?death-date=1871-10-18T12:00:00Z"),
      search("Patient?death-date=gt1871-10-18"),
      search("Patient?_lastUpdated=gt2000-01-01"),
      search("Patient?_lastUpdated=lt2000-01-01"),
    ],
  },
  {
    name: "search: references, quantities, chains and includes",
    steps: [
      ...people,
      ...clinical,
      search((v) => `Observation?subject=Patient/${v.ada}`),
      search((v) => `Observation?subject=${v.ada}`),
      search((v) => `Observation?patient=${v.charles}`),
      search((v) => `Observation?subject:Patient=${v.ada}`),
      search((v) => `Observation?performer=Practitioner/${v.mary}`),
      search((v) => `Observation?performer=${v.mary}`),
      search((v) => `Observation?subject:not=Patient/${v.ada}`),
      search("Observation?performer:missing=true"),
      search("Observation?code=8867-4"),
      search("Observation?code=http://loinc.org|8867-4"),
      search("Observation?code=http://loinc.org|"),
      search("Observation?code:text=heart"),
      search("Observation?code:not=8867-4"),
      search("Observation?category=vital-signs"),
      search("Observation?status=final"),
      search("Observation?status=final,preliminary"),
      search("Observation?value-quantity=72"),
      search("Observation?value-quantity=gt100"),
      search("Observation?value-quantity=le72"),
      search("Observation?value-quantity=ap60"),
      search("Observation?value-quantity=72|http://unitsofmeasure.org|/min"),
      search("Observation?date=2024-03-01T10:00:00Z"),
      search("Observation?date=ge2024-03-01"),
      search("Observation?date=lt2024-02-01"),
      search("Observation?subject.name=lovelace"),
      search("Observation?subject:Patient.name=lovelace"),
      search("Observation?subject:Patient.gender=male"),
      search((v) => `Observation?subject._id=${v.ada}`),
      search("Observation?performer:Practitioner.family=somerville"),
      search("Patient?_has:Observation:subject:status=preliminary"),
      search("Patient?_has:Observation:subject:code=29463-7"),
      search("Encounter?subject.name=ada&participant.family=somerville"),
      search("Condition?encounter.subject.name=ada"),
      search("Observation?_include=Observation:subject"),
      search("Observation?_include=Observation:performer&code=8867-4"),
      search("Observation?_include=Observation:subject:Patient&_include=Observation:performer"),
      search("Patient?_revinclude=Observation:subject&name=ada"),
      search("Condition?_include=Condition:encounter&_include:iterate=Encounter:service-provider"),
      search("Encounter?_include=Encounter:participant"),
      search("Organization?name=analytical"),
      search("Organization?identifier=AE"),
      search("Practitioner?name=mary"),
      search("Condition?code=http://snomed.info/sct|38341003"),
      search("Condition?clinical-status=active"),
      search("Condition?onset-date=2020-05-05"),
      search((v) => `Condition?encounter=Encounter/${v.encounter}`),
      search("Observation?subject.bogus=1"),
      search("Observation?bogus.name=1"),
    ],
  },
  {
    name: "search: paging, sorting, totals and summaries",
    steps: [
      ...people,
      search("Patient?_count=2"),
      search("Patient?_count=2&_offset=2"),
      search("Patient?_count=2&_offset=4"),
      search("Patient?_count=2&_offset=10"),
      search("Patient?_count=0"),
      search("Patient?_count=0&_total=accurate"),
      search("Patient?_total=accurate"),
      search("Patient?_total=estimate&_count=1"),
      search("Patient?_total=none"),
      search("Patient?_summary=count"),
      search("Patient?_summary=true&_sort=birthdate"),
      search("Patient?_summary=data&_sort=birthdate"),
      search("Patient?_summary=text&_sort=birthdate"),
      search("Patient?_elements=gender,birthDate&_sort=birthdate"),
      search("Patient?_fields=name&_sort=-birthdate"),
      search("Patient?_sort=birthdate"),
      search("Patient?_sort=-birthdate"),
      search("Patient?_sort=family"),
      search("Patient?_sort=-family"),
      search("Patient?_sort=given"),
      search("Patient?_sort=name"),
      search("Patient?_sort=gender,-birthdate"),
      search("Patient?_sort=identifier"),
      search("Patient?_sort=address-city"),
      search("Patient?_sort=active"),
      // Ids differ between the sides, so an id order can only be compared as a set.
      { ...search("Patient?_sort=_id"), unordered: true },
      search("Patient?_sort=_lastUpdated&_count=20"),
      search("Patient?_sort=-_lastUpdated&_count=2"),
      search("Patient?_sort=bogus"),
      search("Patient?_count=1001&_sort=birthdate"),
      search("Patient?_count=abc"),
      search("Patient?_offset=-1&_count=1&_sort=birthdate"),
    ],
  },
  {
    name: "search: special parameters and errors",
    steps: [
      ...people,
      search((v) => `Patient?_id=${v.ada}`),
      search((v) => `Patient?_id=${v.ada},${v.grace}`),
      search((v) => `Patient?_id:not=${v.ada}`),
      search("Patient?_id=not-a-uuid"),
      search((v) => `Patient?_id=Patient/${v.grace}`),
      search("Patient?_filter=name%20eq%20ada"),
      search("Patient?_filter=gender%20eq%20male%20and%20birthdate%20gt%201900-01-01"),
      search("Patient?_filter=name%20eq%20ada%20or%20name%20eq%20grace"),
      search("Patient?_filter=not%20(gender%20eq%20male)"),
      search("Patient?_filter=bogus%20eq%201"),
      search("Patient?_filter=name%20eq"),
      search("Patient?bogus=1"),
      search("Patient?name:bogus=1"),
      search("Patient?gender:in=http://hl7.org/fhir/ValueSet/administrative-gender"),
      search("Patient?birthdate:not=1815-12-10"),
      search("Patient?_deleted=true"),
      search((v) => `Patient?_compartment=Patient/${v.ada}`),
      search("Patient?_project:missing=true"),
      search("Binary"),
      search("NotAType?name=x"),
      search("Patient?name=%00"),
      search("Observation?value-quantity=abc"),
      search("Observation?value-quantity=|kg"),
      search("Patient?_include=Patient"),
      search("Patient?_include=*"),
      search("Patient?_revinclude=Observation:bogus"),
      search("Patient?_type=Patient"),
      {
        method: "GET",
        path: "/fhir/R4?_type=Patient,Organization&_count=3&_sort=-_lastUpdated",
        name: "system search across types",
      },
      { method: "GET", path: "/fhir/R4", name: "system search without types" },
      {
        method: "POST",
        path: "/fhir/R4/Patient/_search",
        raw: "name=ada&_count=5",
        contentType: "application/x-www-form-urlencoded",
      },
    ],
  },
  {
    name: "search: deleted and updated resources",
    steps: [
      create({ resourceType: "Patient", name: [{ family: "First" }] }, "first"),
      create({ resourceType: "Patient", name: [{ family: "Second" }] }, "second"),
      create({ resourceType: "Patient", name: [{ family: "Third" }] }, "third"),
      { method: "DELETE", path: (v) => `/fhir/R4/Patient/${v.second}` },
      {
        method: "PUT",
        path: (v) => `/fhir/R4/Patient/${v.first}`,
        body: (v) => ({ resourceType: "Patient", id: v.first, name: [{ family: "Renamed" }] }),
      },
      search("Patient?name=second"),
      search("Patient?name=first"),
      search("Patient?name=renamed"),
      search("Patient?_total=accurate"),
      search("Patient?_deleted=true&_count=5"),
      search("Patient?_sort=_lastUpdated"),
    ],
  },
]
