import {
  listOperations,
  type OpenAPIDocument,
  parseOpenAPIDocument,
} from "@crvouga/mockingbird-openapi"
import { operationMetadata, validateMetadata } from "@crvouga/mockingbird-openapi-metadata"
import { parse as parseYaml } from "yaml"

export type GeneratedFiles = {
  /** `src/generated/openapi.ts` */
  module: string
  /** `SUPPORT.md` */
  support: string
}

export class SpecValidationError extends Error {
  constructor(readonly problems: string[]) {
    super(`openapi.yaml is invalid:\n${problems.map((p) => `  - ${p}`).join("\n")}`)
    this.name = "SpecValidationError"
  }
}

/** Parse and fully validate a provider spec (structure + Mockingbird metadata). */
export const loadSpec = (yamlText: string): OpenAPIDocument => {
  const raw: unknown = parseYaml(yamlText)
  const document = parseOpenAPIDocument(raw)
  const problems = validateMetadata(document)
  if (problems.length > 0) throw new SpecValidationError(problems)
  return document
}

const header =
  "// Generated by @crvouga/mockingbird-openapi-codegen from openapi.yaml. Do not edit.\n"

/** Render the portable module: the document embedded as JSON plus a union of operation ids. */
export const renderModule = (document: OpenAPIDocument): string => {
  const operations = listOperations(document)
  const ids = operations.map((operation) => operation.operationId)
  const supported = operations
    .filter((operation) => operationMetadata(operation.operation).supported)
    .map((operation) => operation.operationId)
  const literal = (values: string[]) =>
    values.length === 0 ? "never" : values.map((v) => JSON.stringify(v)).join(" | ")
  const json = JSON.stringify(document)
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${")
  return [
    header,
    'import type { OpenAPIDocument } from "@crvouga/mockingbird-openapi"',
    "",
    `export const document: OpenAPIDocument = JSON.parse(\`${json}\`) as OpenAPIDocument`,
    "",
    `export type OperationId = ${literal(ids)}`,
    `export type SupportedOperationId = ${literal(supported)}`,
    `export const operationIds = ${JSON.stringify(ids)} as const`,
    `export const supportedOperationIds = ${JSON.stringify(supported)} as const`,
    "",
  ].join("\n")
}

/** Render the coverage matrix. */
export const renderSupport = (document: OpenAPIDocument): string => {
  const operations = listOperations(document)
  const rows = operations.map((operation) => {
    const meta = operationMetadata(operation.operation)
    const status = meta.supported ? "✅ supported" : "❌ unsupported"
    const parity = !meta.supported
      ? "—"
      : meta.parity.enabled
        ? meta.parity.safe
          ? "✅"
          : "⚠️ unsafe (opt-in)"
        : "❌ disabled"
    const reason = meta.reason ?? meta.parity.reason ?? ""
    return `| \`${operation.operationId}\` | \`${operation.method.toUpperCase()} ${operation.path}\` | ${status} | ${parity} | ${reason} |`
  })
  const supported = operations.filter((o) => operationMetadata(o.operation).supported).length
  const parityEnabled = operations.filter(
    (o) => operationMetadata(o.operation).parity.enabled,
  ).length
  return [
    `# ${document.info.title} — operation support`,
    "",
    "Generated from `openapi.yaml`; do not edit by hand.",
    "",
    `- operations in spec: **${operations.length}**`,
    `- supported by the mock: **${supported}**`,
    `- parity enabled: **${parityEnabled}**`,
    "",
    "| operationId | route | mock | parity | notes |",
    "| --- | --- | --- | --- | --- |",
    ...rows,
    "",
  ].join("\n")
}

export const generate = (yamlText: string): GeneratedFiles => {
  const document = loadSpec(yamlText)
  return { module: renderModule(document), support: renderSupport(document) }
}
