/**
 * Operations beyond customers, products and prices. They are parity-enabled but `safe: false`
 * so live differential runs stay on the field-matched core, while self-parity walks (which pass
 * `includeUnsafe`) exercise the whole surface.
 */
export type SurfaceOp = {
  path?: Record<string, string>
  /** Top-level body or query field → resource type. */
  refs?: Record<string, string>
  /** Resource type for ending_before / starting_after. */
  cursor?: string
  /** `arrayField.itemField` → resource type. */
  arrayRefs?: Record<string, string>
}

export const SURFACE: Record<string, SurfaceOp> = {
  PostPaymentMethods: { refs: { customer: "customer" } },
  GetPaymentMethods: { cursor: "payment_method", refs: { customer: "customer" } },
  GetPaymentMethodsPaymentMethod: { path: { payment_method: "payment_method" } },
  PostPaymentMethodsPaymentMethod: { path: { payment_method: "payment_method" } },
  PostPaymentMethodsPaymentMethodAttach: {
    path: { payment_method: "payment_method" },
    refs: { customer: "customer" },
  },
  PostPaymentMethodsPaymentMethodDetach: { path: { payment_method: "payment_method" } },
  PostPaymentIntents: { refs: { customer: "customer", payment_method: "payment_method" } },
  GetPaymentIntents: { cursor: "payment_intent", refs: { customer: "customer" } },
  GetPaymentIntentsIntent: { path: { intent: "payment_intent" } },
  PostPaymentIntentsIntent: {
    path: { intent: "payment_intent" },
    refs: { customer: "customer", payment_method: "payment_method" },
  },
  PostPaymentIntentsIntentConfirm: {
    path: { intent: "payment_intent" },
    refs: { payment_method: "payment_method" },
  },
  PostPaymentIntentsIntentCapture: { path: { intent: "payment_intent" } },
  PostPaymentIntentsIntentCancel: { path: { intent: "payment_intent" } },
  GetPaymentIntentsSearch: {},
  PostSetupIntents: { refs: { customer: "customer", payment_method: "payment_method" } },
  GetSetupIntents: { cursor: "setup_intent", refs: { customer: "customer" } },
  GetSetupIntentsIntent: { path: { intent: "setup_intent" } },
  PostSetupIntentsIntent: {
    path: { intent: "setup_intent" },
    refs: { customer: "customer", payment_method: "payment_method" },
  },
  PostSetupIntentsIntentConfirm: {
    path: { intent: "setup_intent" },
    refs: { payment_method: "payment_method" },
  },
  PostSetupIntentsIntentCancel: { path: { intent: "setup_intent" } },
  PostCharges: { refs: { customer: "customer" } },
  GetCharges: {
    cursor: "charge",
    refs: { customer: "customer", payment_intent: "payment_intent" },
  },
  GetChargesCharge: { path: { charge: "charge" } },
  PostChargesCharge: { path: { charge: "charge" } },
  PostChargesChargeCapture: { path: { charge: "charge" } },
  GetChargesSearch: {},
  GetChargesChargeRefunds: { path: { charge: "charge" }, cursor: "refund" },
  PostChargesChargeRefunds: { path: { charge: "charge" } },
  GetChargesChargeRefundsRefund: { path: { charge: "charge", refund: "refund" } },
  PostChargesChargeRefundsRefund: { path: { charge: "charge", refund: "refund" } },
  PostRefunds: { refs: { charge: "charge", payment_intent: "payment_intent" } },
  GetRefunds: { cursor: "refund", refs: { charge: "charge", payment_intent: "payment_intent" } },
  GetRefundsRefund: { path: { refund: "refund" } },
  PostRefundsRefund: { path: { refund: "refund" } },
  PostRefundsRefundCancel: { path: { refund: "refund" } },
  PostTokens: {},
  GetTokensToken: { path: { token: "token" } },
  PostSources: {},
  GetSourcesSource: { path: { source: "source" } },
  PostSourcesSource: { path: { source: "source" } },
  GetConfirmationTokensConfirmationToken: { path: { confirmation_token: "confirmation_token" } },
  PostTestHelpersConfirmationTokens: {},
  GetMandatesMandate: { path: { mandate: "mandate" } },
  GetCustomersSearch: {},
  GetCustomersCustomerPaymentMethods: { path: { customer: "customer" }, cursor: "payment_method" },
  GetCustomersCustomerBalanceTransactions: {
    path: { customer: "customer" },
    cursor: "customer_balance_transaction",
  },
  PostCustomersCustomerBalanceTransactions: { path: { customer: "customer" } },
  GetCustomersCustomerBalanceTransactionsTransaction: {
    path: { customer: "customer", transaction: "customer_balance_transaction" },
  },
  GetProductsSearch: {},
  GetPricesSearch: {},
  PostCoupons: {},
  GetCoupons: { cursor: "coupon" },
  GetCouponsCoupon: { path: { coupon: "coupon" } },
  PostCouponsCoupon: { path: { coupon: "coupon" } },
  DeleteCouponsCoupon: { path: { coupon: "coupon" } },
  PostPromotionCodes: { refs: { coupon: "coupon", customer: "customer" } },
  GetPromotionCodes: { cursor: "promotion_code", refs: { coupon: "coupon" } },
  GetPromotionCodesPromotionCode: { path: { promotion_code: "promotion_code" } },
  PostPromotionCodesPromotionCode: { path: { promotion_code: "promotion_code" } },
  PostTaxRates: {},
  GetTaxRates: { cursor: "tax_rate" },
  GetTaxRatesTaxRate: { path: { tax_rate: "tax_rate" } },
  PostTaxRatesTaxRate: { path: { tax_rate: "tax_rate" } },
  PostSubscriptions: {
    refs: { customer: "customer", default_payment_method: "payment_method" },
    arrayRefs: { "items.price": "price" },
  },
  GetSubscriptions: { cursor: "subscription", refs: { customer: "customer", price: "price" } },
  GetSubscriptionsSubscriptionExposedId: { path: { subscription_exposed_id: "subscription" } },
  PostSubscriptionsSubscriptionExposedId: {
    path: { subscription_exposed_id: "subscription" },
    refs: { default_payment_method: "payment_method" },
  },
  DeleteSubscriptionsSubscriptionExposedId: { path: { subscription_exposed_id: "subscription" } },
  GetSubscriptionsSearch: {},
  PostSubscriptionsSubscriptionResume: { path: { subscription: "subscription" } },
  PostSubscriptionItems: { refs: { subscription: "subscription", price: "price" } },
  GetSubscriptionItems: { cursor: "subscription_item", refs: { subscription: "subscription" } },
  GetSubscriptionItemsItem: { path: { item: "subscription_item" } },
  PostSubscriptionItemsItem: { path: { item: "subscription_item" }, refs: { price: "price" } },
  DeleteSubscriptionItemsItem: { path: { item: "subscription_item" } },
  PostInvoices: {
    refs: {
      customer: "customer",
      subscription: "subscription",
      default_payment_method: "payment_method",
    },
  },
  GetInvoices: { cursor: "invoice", refs: { customer: "customer", subscription: "subscription" } },
  GetInvoicesInvoice: { path: { invoice: "invoice" } },
  PostInvoicesInvoice: { path: { invoice: "invoice" } },
  DeleteInvoicesInvoice: { path: { invoice: "invoice" } },
  PostInvoicesInvoiceFinalize: { path: { invoice: "invoice" } },
  PostInvoicesInvoicePay: {
    path: { invoice: "invoice" },
    refs: { payment_method: "payment_method" },
  },
  PostInvoicesInvoiceVoid: { path: { invoice: "invoice" } },
  PostInvoicesInvoiceSend: { path: { invoice: "invoice" } },
  GetInvoicesInvoiceLines: { path: { invoice: "invoice" } },
  GetInvoicesSearch: {},
  PostInvoicesCreatePreview: { refs: { customer: "customer", subscription: "subscription" } },
  PostInvoiceitems: { refs: { customer: "customer", invoice: "invoice", price: "price" } },
  GetInvoiceitems: { cursor: "invoiceitem", refs: { customer: "customer" } },
  GetInvoiceitemsInvoiceitem: { path: { invoiceitem: "invoiceitem" } },
  PostInvoiceitemsInvoiceitem: { path: { invoiceitem: "invoiceitem" } },
  DeleteInvoiceitemsInvoiceitem: { path: { invoiceitem: "invoiceitem" } },
  PostCheckoutSessions: {
    refs: { customer: "customer" },
    arrayRefs: { "line_items.price": "price" },
  },
  GetCheckoutSessions: { cursor: "checkout_session" },
  GetCheckoutSessionsSession: { path: { session: "checkout_session" } },
  PostCheckoutSessionsSession: { path: { session: "checkout_session" } },
  PostCheckoutSessionsSessionExpire: { path: { session: "checkout_session" } },
  GetCheckoutSessionsSessionLineItems: { path: { session: "checkout_session" } },
  PostPaymentLinks: { arrayRefs: { "line_items.price": "price" } },
  GetPaymentLinks: { cursor: "payment_link" },
  GetPaymentLinksPaymentLink: { path: { payment_link: "payment_link" } },
  PostPaymentLinksPaymentLink: { path: { payment_link: "payment_link" } },
  GetPaymentLinksPaymentLinkLineItems: { path: { payment_link: "payment_link" } },
  PostBillingPortalSessions: { refs: { customer: "customer" } },
  PostCustomerSessions: { refs: { customer: "customer" } },
  PostEphemeralKeys: { refs: { customer: "customer" } },
  DeleteEphemeralKeysKey: { path: { key: "ephemeral_key" } },
  PostWebhookEndpoints: {},
  GetWebhookEndpoints: { cursor: "webhook_endpoint" },
  GetWebhookEndpointsWebhookEndpoint: { path: { webhook_endpoint: "webhook_endpoint" } },
  PostWebhookEndpointsWebhookEndpoint: { path: { webhook_endpoint: "webhook_endpoint" } },
  DeleteWebhookEndpointsWebhookEndpoint: { path: { webhook_endpoint: "webhook_endpoint" } },
  PostPayouts: {},
  GetPayouts: { cursor: "payout" },
  GetPayoutsPayout: { path: { payout: "payout" } },
  PostPayoutsPayout: { path: { payout: "payout" } },
  PostPayoutsPayoutCancel: { path: { payout: "payout" } },
  GetDisputes: { cursor: "dispute" },
  GetDisputesDispute: { path: { dispute: "dispute" } },
  GetBalance: {},
  GetBalanceTransactions: { cursor: "balance_transaction" },
  GetBalanceTransactionsId: { path: { id: "balance_transaction" } },
  GetEvents: { cursor: "event" },
  GetEventsId: { path: { id: "event" } },
  GetAccount: {},
}

/** Response fields that are resource ids (string or expandable). */
export const IDENTITIES: Record<string, Record<string, string>> = {
  payment_intent: {
    id: "payment_intent",
    customer: "customer",
    payment_method: "payment_method",
    latest_charge: "charge",
  },
  setup_intent: {
    id: "setup_intent",
    customer: "customer",
    payment_method: "payment_method",
    mandate: "mandate",
  },
  payment_method: { id: "payment_method", customer: "customer" },
  charge: {
    id: "charge",
    customer: "customer",
    payment_intent: "payment_intent",
    balance_transaction: "balance_transaction",
  },
  refund: { id: "refund", charge: "charge", payment_intent: "payment_intent" },
  token: { id: "token" },
  confirmation_token: { id: "confirmation_token" },
  mandate: { id: "mandate", payment_method: "payment_method" },
  source: { id: "source" },
  coupon: { id: "coupon" },
  deleted_coupon: { id: "coupon" },
  promotion_code: { id: "promotion_code" },
  tax_rate: { id: "tax_rate" },
  subscription: {
    id: "subscription",
    customer: "customer",
    default_payment_method: "payment_method",
    latest_invoice: "invoice",
  },
  subscription_item: { id: "subscription_item", subscription: "subscription" },
  deleted_subscription_item: { id: "subscription_item" },
  invoice: { id: "invoice", customer: "customer" },
  deleted_invoice: { id: "invoice" },
  invoiceitem: { id: "invoiceitem", customer: "customer", invoice: "invoice" },
  deleted_invoiceitem: { id: "invoiceitem" },
  customer_balance_transaction: { id: "customer_balance_transaction", customer: "customer" },
  "checkout.session": {
    id: "checkout_session",
    customer: "customer",
    payment_intent: "payment_intent",
    setup_intent: "setup_intent",
    subscription: "subscription",
  },
  payment_link: { id: "payment_link" },
  "billing_portal.session": { id: "billing_portal_session", customer: "customer" },
  webhook_endpoint: { id: "webhook_endpoint" },
  deleted_webhook_endpoint: { id: "webhook_endpoint" },
  payout: { id: "payout" },
  balance_transaction: { id: "balance_transaction" },
  event: { id: "event" },
  ephemeral_key: { id: "ephemeral_key" },
  dispute: { id: "dispute", charge: "charge" },
}

export const MISSING_ID: Record<string, string> = {
  customer: "cus_mockingbird_missing",
  product: "prod_mockingbird_missing",
  price: "price_mockingbird_missing",
  payment_method: "pm_mockingbird_missing",
  payment_intent: "pi_mockingbird_missing",
  setup_intent: "seti_mockingbird_missing",
  charge: "ch_mockingbird_missing",
  refund: "re_mockingbird_missing",
  token: "tok_mockingbird_missing",
  confirmation_token: "ctoken_mockingbird_missing",
  mandate: "mandate_mockingbird_missing",
  source: "src_mockingbird_missing",
  coupon: "coupon_mockingbird_missing",
  promotion_code: "promo_mockingbird_missing",
  tax_rate: "txr_mockingbird_missing",
  subscription: "sub_mockingbird_missing",
  subscription_item: "si_mockingbird_missing",
  invoice: "in_mockingbird_missing",
  invoiceitem: "ii_mockingbird_missing",
  customer_balance_transaction: "cbtxn_mockingbird_missing",
  checkout_session: "cs_mockingbird_missing",
  payment_link: "plink_mockingbird_missing",
  billing_portal_session: "bps_mockingbird_missing",
  webhook_endpoint: "we_mockingbird_missing",
  payout: "po_mockingbird_missing",
  dispute: "dp_mockingbird_missing",
  balance_transaction: "txn_mockingbird_missing",
  event: "evt_mockingbird_missing",
  ephemeral_key: "ephkey_mockingbird_missing",
}
