/**
 * From a matched script turn (or the unscripted default) to a concrete answer: the content
 * blocks, stop reason, usage and trace, and the fault to inject. Rendering into Converse
 * JSON, event-stream frames, an Anthropic Messages body or harness events happens in
 * `render.ts`; this module decides *what* the model says, independent of the wire.
 */
import { sampleSchema } from "./schema-sample.js"
import type { CallAnalysis, ScriptTurn, ScriptUsage, StopReason, TurnFault } from "./scripts.js"
import { turnFault } from "./scripts.js"

export type PlanBlock =
  | { kind: "text"; text: string }
  | { kind: "reasoning"; text: string }
  | { kind: "toolUse"; toolUseId: string; name: string; input: unknown }
  | { kind: "toolResult"; toolUseId: string; content: unknown[] }

export type Usage = {
  inputTokens: number
  outputTokens: number
  totalTokens: number
  cacheReadInputTokens?: number
  cacheWriteInputTokens?: number
}

export type Plan = {
  /** The script that answered, or `undefined` for the unscripted default. */
  scriptId: string | undefined
  /** Which default answered, when unscripted: `chat`, `structured`, `classifier`, `scribe`, `titan`, `harness`, `sonic`. */
  fallback?: string
  blocks: PlanBlock[]
  stopReason: StopReason
  usage: Usage
  trace?: Record<string, unknown>
  fault?: TurnFault
  chunkSize: number
  delayMsPerChunk: number
  userTranscript?: string
}

/** Bedrock's canned guardrail refusal. */
export const GUARDRAIL_BLOCKED_TEXT = "Sorry, the model cannot answer this question."

/** What an unscripted chat call says. Deliberately content-free (never an echo). */
export const DEFAULT_CHAT_TEXT = "OK."

export const DEFAULT_CLASSIFIER = { category: "general", confidence: 0.9 }

export const DEFAULT_SOAP_NOTE = {
  sections: [
    {
      title: "Subjective",
      content: "Patient reports no new concerns. [UNCERTAIN] Mock transcript.",
    },
    { title: "Objective", content: "No examination findings discussed." },
    {
      title: "Assessment",
      content: "Stable. [UNCERTAIN] Generated by the Mockingbird Bedrock mock.",
    },
    { title: "Plan", content: "Continue current plan; follow up as scheduled." },
  ],
  summary: "Routine follow-up visit with no new concerns (mock note).",
}

const tokens = (chars: number) => Math.max(1, Math.ceil(chars / 4))

const defaultTrace = (guardrailId: string | undefined): Record<string, unknown> => ({
  guardrail: {
    actionReason: "Guardrail blocked.",
    inputAssessment: {
      [guardrailId ?? "mock-guardrail"]: {
        topicPolicy: {
          topics: [{ name: "Medical Advice", type: "DENY", action: "BLOCKED", detected: true }],
        },
        invocationMetrics: {
          guardrailProcessingLatency: 120,
          usage: {
            topicPolicyUnits: 1,
            contentPolicyUnits: 0,
            wordPolicyUnits: 0,
            sensitiveInformationPolicyUnits: 0,
            sensitiveInformationPolicyFreeUnits: 0,
            contextualGroundingPolicyUnits: 0,
          },
          guardrailCoverage: { textCharacters: { guarded: 1, total: 1 } },
        },
      },
    },
  },
})

export type PlanContext = {
  /** Deterministic tool-use ids. */
  nextToolUseId: () => string
  chunkSize: number
  delayMsPerChunk: number
  guardrailId?: string
  traceEnabled: boolean
  /** `inferenceConfig.maxTokens` (or `max_tokens`), when the caller capped output. */
  maxTokens?: number
}

const withUsage = (
  call: CallAnalysis,
  blocks: PlanBlock[],
  scripted: ScriptUsage | undefined,
): Usage => {
  const outputChars = blocks.reduce(
    (sum, block) =>
      sum +
      (block.kind === "toolUse"
        ? JSON.stringify(block.input ?? {}).length
        : block.kind === "toolResult"
          ? JSON.stringify(block.content).length
          : block.text.length),
    0,
  )
  const inputTokens = scripted?.inputTokens ?? tokens(call.inputChars)
  const outputTokens = scripted?.outputTokens ?? tokens(outputChars)
  return {
    inputTokens,
    outputTokens,
    totalTokens: scripted?.totalTokens ?? inputTokens + outputTokens,
    ...(scripted?.cacheReadInputTokens !== undefined || call.hasCachePoint
      ? { cacheReadInputTokens: scripted?.cacheReadInputTokens ?? 0 }
      : {}),
    ...(scripted?.cacheWriteInputTokens !== undefined || call.hasCachePoint
      ? { cacheWriteInputTokens: scripted?.cacheWriteInputTokens ?? 0 }
      : {}),
  }
}

/** Structured output rendered in the form the request asked for. */
const renderJson = (
  call: CallAnalysis,
  value: unknown,
  context: PlanContext,
): { blocks: PlanBlock[]; stopReason: StopReason } => {
  const structured = call.structured
  if (structured?.form === "tool") {
    return {
      blocks: [
        {
          kind: "toolUse",
          toolUseId: context.nextToolUseId(),
          name: structured.tool,
          input: value,
        },
      ],
      stopReason: "tool_use",
    }
  }
  return { blocks: [{ kind: "text", text: JSON.stringify(value) }], stopReason: "end_turn" }
}

/** Apply a `maxTokens` cap: text beyond it is cut and the stop reason becomes `max_tokens`. */
const capOutput = (
  blocks: PlanBlock[],
  stopReason: StopReason,
  maxTokens: number | undefined,
  force: boolean,
) => {
  const budget = force ? undefined : maxTokens !== undefined ? maxTokens * 4 : undefined
  const texts = blocks.filter((b): b is PlanBlock & { kind: "text" } => b.kind === "text")
  const length = texts.reduce((sum, b) => sum + b.text.length, 0)
  if (!force && (budget === undefined || length <= budget)) return { blocks, stopReason }
  let remaining = force ? Math.max(1, Math.floor(length / 2)) : (budget as number)
  const out: PlanBlock[] = []
  for (const block of blocks) {
    if (block.kind === "toolUse" || block.kind === "toolResult") continue
    if (block.kind === "reasoning") {
      out.push(block)
      continue
    }
    if (remaining <= 0) break
    out.push({ kind: "text", text: block.text.slice(0, remaining) })
    remaining -= block.text.length
  }
  return { blocks: out, stopReason: "max_tokens" as StopReason }
}

/** The plan for a scripted turn. */
export const planTurn = (
  scriptId: string,
  turn: ScriptTurn,
  call: CallAnalysis,
  context: PlanContext,
): Plan => {
  let blocks: PlanBlock[] = []
  let stopReason: StopReason | undefined
  let trace: Record<string, unknown> | undefined
  if (turn.reasoning) blocks.push({ kind: "reasoning", text: turn.reasoning })
  if (turn.guardrail) {
    const detail = typeof turn.guardrail === "object" ? turn.guardrail : {}
    blocks.push({ kind: "text", text: detail.text ?? GUARDRAIL_BLOCKED_TEXT })
    stopReason = "guardrail_intervened"
    if (context.traceEnabled || detail.trace !== undefined) {
      trace =
        (detail.trace as Record<string, unknown> | undefined) ?? defaultTrace(context.guardrailId)
    }
  } else {
    if (turn.text !== undefined) blocks.push({ kind: "text", text: turn.text })
    if (turn.json !== undefined) {
      const rendered = renderJson(call, turn.json, context)
      blocks.push(...rendered.blocks)
      stopReason = rendered.stopReason
    }
    if (turn.toolResult !== undefined) {
      blocks.push({
        kind: "toolResult",
        toolUseId: context.nextToolUseId(),
        content: turn.toolResult,
      })
    }
    const uses =
      turn.toolUse === undefined ? [] : Array.isArray(turn.toolUse) ? turn.toolUse : [turn.toolUse]
    for (const use of uses) {
      blocks.push({
        kind: "toolUse",
        toolUseId: use.toolUseId ?? context.nextToolUseId(),
        name: use.name,
        input: use.input ?? {},
      })
      stopReason = "tool_use"
    }
  }
  const fault = turnFault(turn)
  const capped = capOutput(
    blocks,
    turn.stopReason ?? stopReason ?? "end_turn",
    context.maxTokens,
    fault?.type === "max_tokens",
  )
  blocks = capped.blocks
  return {
    scriptId,
    blocks,
    stopReason: turn.stopReason ?? capped.stopReason,
    usage: withUsage(call, blocks, turn.usage),
    ...(trace ? { trace } : {}),
    ...(fault && fault.type !== "max_tokens" ? { fault } : {}),
    chunkSize: turn.chunkSize ?? context.chunkSize,
    delayMsPerChunk: turn.delayMsPerChunk ?? context.delayMsPerChunk,
    ...(turn.userTranscript !== undefined ? { userTranscript: turn.userTranscript } : {}),
  }
}

/** Heuristic: our intent classifier's system prompt asks for this exact shape. */
const isClassifier = (call: CallAnalysis) =>
  call.systemText.includes('"category"') && call.systemText.includes('"confidence"')

/** The unscripted answer: echo-free text, or a schema-valid minimal object. */
export const planDefault = (
  call: CallAnalysis,
  context: PlanContext,
  defaultText: string,
): Plan => {
  let blocks: PlanBlock[]
  let stopReason: StopReason = "end_turn"
  let fallback = "chat"
  if (call.structured) {
    const value = sampleSchema(call.structured.schema ?? {})
    const rendered = renderJson(call, value, context)
    blocks = rendered.blocks
    stopReason = rendered.stopReason
    fallback = "structured"
  } else if (call.operation === "InvokeModel") {
    blocks = [{ kind: "text", text: JSON.stringify(DEFAULT_SOAP_NOTE) }]
    fallback = "scribe"
  } else if (isClassifier(call)) {
    blocks = [{ kind: "text", text: JSON.stringify(DEFAULT_CLASSIFIER) }]
    fallback = "classifier"
  } else {
    blocks = [{ kind: "text", text: defaultText }]
  }
  const capped = capOutput(blocks, stopReason, context.maxTokens, false)
  return {
    scriptId: undefined,
    fallback,
    blocks: capped.blocks,
    stopReason: capped.stopReason,
    usage: withUsage(call, capped.blocks, undefined),
    chunkSize: context.chunkSize,
    delayMsPerChunk: context.delayMsPerChunk,
  }
}

/** Cut a plan's text in half and stop with `max_tokens` (the `max_tokens` fault preset). */
export const truncatePlan = (plan: Plan): Plan => {
  const capped = capOutput(plan.blocks, plan.stopReason, undefined, true)
  return { ...plan, blocks: capped.blocks, stopReason: capped.stopReason }
}

/** Split `text` into `size`-character chunks (at least one, possibly empty). */
export const chunk = (text: string, size: number): string[] => {
  if (text.length === 0) return [""]
  const out: string[] = []
  for (let i = 0; i < text.length; i += Math.max(1, size))
    out.push(text.slice(i, i + Math.max(1, size)))
  return out
}
