/**
 * Boilerplate templates for the mockingbird init command.
 */

export type ProviderTemplate = {
  /** Short name, e.g. "stripe" */
  name: string
  /** npm package name */
  pkg: string
  /** Import statement */
  importStatement: string
  /** Instance creation line */
  instanceLine: string
  /** Return field name */
  field: string
}

const PROVIDER_TEMPLATES: Record<string, (name: string) => ProviderTemplate> = {
  stripe: () => ({
    name: "stripe",
    pkg: "@crvouga/mockingbird-service-stripe",
    importStatement: `import { StripeAPI, document as stripeDocument } from "@crvouga/mockingbird-service-stripe"`,
    instanceLine: `const stripe = new StripeAPI({ sqlite, document: stripeDocument })`,
    field: "stripe",
  }),
  junction: () => ({
    name: "junction",
    pkg: "@crvouga/mockingbird-service-junction",
    importStatement: `import { JunctionAPI, document as junctionDocument } from "@crvouga/mockingbird-service-junction"`,
    instanceLine: `const junction = new JunctionAPI({ sqlite, document: junctionDocument })`,
    field: "junction",
  }),
  genebygene: () => ({
    name: "genebygene",
    pkg: "@crvouga/mockingbird-service-genebygene",
    importStatement: `import { GeneByGeneAPI, document as genebygeneDocument } from "@crvouga/mockingbird-service-genebygene"`,
    instanceLine: `const genebygene = new GeneByGeneAPI({ sqlite, document: genebygeneDocument })`,
    field: "genebygene",
  }),
  medplum: () => ({
    name: "medplum",
    pkg: "@crvouga/mockingbird-service-medplum",
    importStatement: `import { MedplumAPI, document as medplumDocument } from "@crvouga/mockingbird-service-medplum"`,
    instanceLine: `const medplum = new MedplumAPI({ sqlite, document: medplumDocument })`,
    field: "medplum",
  }),
}

export function getProviderTemplate(name: string): ProviderTemplate | undefined {
  const factory = PROVIDER_TEMPLATES[name]
  return factory?.(name)
}

export function generateSetupContent(providers: string[], typescript: boolean): string {
  const ts = typescript
  const templates = providers
    .map((p) => getProviderTemplate(p))
    .filter(Boolean) as ProviderTemplate[]

  const imports = [
    `import { createDefaultSqlite } from "@crvouga/mockingbird"`,
    `import { fromFetchHandler${ts ? ", toFetchHandler" : ""} } from "@crvouga/mockingbird"`,
    ...templates.map((t) => t.importStatement),
  ].join("\n")

  const instances = templates.map((t) => `  ${t.instanceLine}`).join("\n")
  const returnFields = templates.map((t) => `    ${t.field},`).join("\n")
  const returnType = ts
    ? `: { ${templates.map((t) => `${t.field}: import("@crvouga/mockingbird-service-${t.name}").default`).join("; ")} }`
    : ""

  return `// Auto-generated by @crvouga/mockingbird init
// Usage: import and call in test setup to get fresh mock instances.

${imports}

export function createMockProviders()${returnType} {
  const sqlite = createDefaultSqlite()

${instances}

  return {
${returnFields}
  }
}

/*
 * Usage example (Bun built-in test runner):
 *
 * const mocks = createMockProviders()
 * const originalFetch = global.fetch
 *
 * beforeAll(() => {
 *   global.fetch = fromFetchHandler(mocks.stripe.fetch)
 * })
 *
 * afterAll(() => {
 *   global.fetch = originalFetch
 * })
 */
`
}

export function generateReadmeSection(providers: string[]): string {
  const providerList =
    providers.length > 0
      ? providers.map((p) => `- \`${getProviderTemplate(p)?.pkg ?? p}\``).join("\n")
      : `- \`@crvouga/mockingbird\``

  return `## Mockingbird

This project uses [Mockingbird](https://github.com/crvouga/mockingbird) for stateful mock HTTP APIs.

${providerList}

### Quick start

\`\`\`typescript
import { createMockProviders } from "./mocks/mockingbird"

const mocks = createMockProviders()
\`\`\`
`
}
