/**
 * Boilerplate templates for the mockingbird init command.
 */

export type ProviderTemplate = {
  /** Short name, e.g. "stripe" */
  name: string
  /** npm package name */
  pkg: string
  /** Class/type name for TypeScript return annotations */
  typeName: string
  /** Import statement */
  importStatement: string
  /** Instance creation line */
  instanceLine: string
  /** Return field name */
  field: string
}

const PROVIDER_TEMPLATES: Record<string, (name: string) => ProviderTemplate> = {
  stripe: () => ({
    name: "stripe",
    pkg: "@crvouga/mockingbird-service-stripe",
    typeName: "StripeAPI",
    importStatement: `import { StripeAPI } from "@crvouga/mockingbird-service-stripe"`,
    instanceLine: `const stripe = new StripeAPI({ sqlite })`,
    field: "stripe",
  }),
  junction: () => ({
    name: "junction",
    pkg: "@crvouga/mockingbird-service-junction",
    typeName: "JunctionAPI",
    importStatement: `import { JunctionAPI } from "@crvouga/mockingbird-service-junction"`,
    instanceLine: `const junction = new JunctionAPI({ sqlite })`,
    field: "junction",
  }),
  genebygene: () => ({
    name: "genebygene",
    pkg: "@crvouga/mockingbird-service-genebygene",
    typeName: "GeneByGeneAPI",
    importStatement: `import { GeneByGeneAPI } from "@crvouga/mockingbird-service-genebygene"`,
    instanceLine: `const genebygene = new GeneByGeneAPI({ sqlite })`,
    field: "genebygene",
  }),
  medplum: () => ({
    name: "medplum",
    pkg: "@crvouga/mockingbird-service-medplum",
    typeName: "MedplumAPI",
    importStatement: `import { MedplumAPI } from "@crvouga/mockingbird-service-medplum"`,
    // Self-hosts the real Medplum server: `await medplum.start()` before use, `stop()` after.
    instanceLine: `const medplum = new MedplumAPI()`,
    field: "medplum",
  }),
}

export function getProviderTemplate(name: string): ProviderTemplate | undefined {
  const factory = PROVIDER_TEMPLATES[name]
  return factory?.(name)
}

export function generateSetupContent(providers: string[], typescript: boolean): string {
  const ts = typescript
  const templates = providers
    .map((p) => getProviderTemplate(p))
    .filter(Boolean) as ProviderTemplate[]
  const sqliteBacked = templates.filter((t) => t.name !== "medplum")

  const imports = [
    ...(sqliteBacked.length > 0
      ? [`import { createDefaultSqlite } from "@crvouga/mockingbird"`]
      : []),
    ...templates.map((t) => t.importStatement),
  ].join("\n")

  const instances = [
    ...(sqliteBacked.length > 0
      ? ["  // One in-memory SQLite database; each service keeps its own namespace in it."]
      : []),
    ...(sqliteBacked.length > 0 ? ["  const sqlite = createDefaultSqlite()"] : []),
    ...templates.map((t) =>
      t.name === "medplum"
        ? `  // Medplum self-hosts the real server: await medplum.start() before use, medplum.stop() after.\n  ${t.instanceLine}`
        : `  ${t.instanceLine}`,
    ),
  ].join("\n")
  const returnFields = templates.map((t) => `    ${t.field},`).join("\n")
  const returnType = ts
    ? `: { ${templates.map((t) => `${t.field}: ${t.typeName}`).join("; ")} }`
    : ""
  const example = templates[0]?.field ?? "stripe"

  return `// Generated by \`mockingbird init\`. Edit freely.
// Docs for agents and humans: node_modules/@crvouga/mockingbird/README.md
${imports}

/** Fresh, isolated mock providers. Create one set per test file (or reset() between tests). */
export function createMockProviders()${returnType} {
${instances}

  return {
${returnFields}
  }
}

/*
 * Each mock is a Fetch handler: \`mock.fetch(request) → Promise<Response>\`.
 *
 * In-process (fastest) — hand the mock's fetch to your API client:
 *
 *   const mocks = createMockProviders()
 *   const res = await mocks.${example}.fetch(new Request("https://mock.local/...", { headers }))
 *
 * Over HTTP — when the code under test needs a base URL (official SDKs, other processes):
 *
 *   import { serve } from "@crvouga/mockingbird-adapter-node"
 *   const server = await serve(mocks.${example}) // node:http Server on an ephemeral port
 *   const { port } = server.address() as import("node:net").AddressInfo
 *   // point the SDK at http://127.0.0.1:\${port}, then server.close() after the tests
 */
`
}
