/**
 * Generate GitHub Release markdown from conventional commits since last tag.
 *
 *   bun scripts/release-notes.ts             → stdout
 *   bun scripts/release-notes.ts --json      → JSON array of commits
 */
import { $ } from "bun"

const root = join(import.meta.dir, "..")

const isJson = process.argv.includes("--json")

// ── Git helpers ────────────────────────────────────────────────────

async function lastTag(): Promise<string | null> {
  const result = await $`git describe --tags --abbrev=0 --match 'v*'`.cwd(root).quiet().nothrow()
  return result.exitCode === 0 ? result.text().trim() : null
}

type Commit = { hash: string; subject: string; body: string }

async function commitsSince(ref: string | null): Promise<Commit[]> {
  const range = ref ? `${ref}..HEAD` : "--root"
  const result = await $`git log --first-parent ${range} --format='%H|||%s|||%b---'`
    .cwd(root)
    .quiet()
  if (result.exitCode !== 0) return []
  const raw = result.text().trim()
  if (!raw) return []
  return raw
    .split("---\n")
    .filter(Boolean)
    .map((block) => {
      const [hash, subject, ...bodyLines] = block.split("|||")
      const h = (hash ?? "").trim()
      // Strip the '---' sentinel from the last body line
      const b = (bodyLines ?? []).join("\n").trim().replace(/---$/, "").trim()
      return { hash: h, subject: (subject ?? "").trim(), body: b }
    })
}

// ── Categorisation ─────────────────────────────────────────────────

type Category = "breaking" | "feat" | "fix" | "other"

function categorise(subject: string, body: string): Category {
  if (/^BREAKING(\s+CHANGE)?:/m.test(body)) return "breaking"
  const m = subject.match(
    /^(build|chore|ci|docs|feat|fix|perf|refactor|style|test)(\([^)]+\))?(!)?:/,
  )
  if (!m) return "other"
  const type = m[1]
  const breaking = m[3] === "!"
  if (breaking) return "breaking"
  if (type === "feat") return "feat"
  if (type === "fix") return "fix"
  return "other"
}

function stripType(subject: string): string {
  return subject.replace(
    /^(build|chore|ci|docs|feat|fix|perf|refactor|style|test)(\([^)]+\))?(!)?:\s*/,
    "",
  )
}

// ── Main ───────────────────────────────────────────────────────────
import { join } from "node:path"

const tag = await lastTag()
const commits = await commitsSince(tag)

if (commits.length === 0) {
  console.log("No commits since last tag.")
  process.exit(0)
}

const shortHashLen = 7

const grouped: Record<Category, { hash: string; subject: string; body: string }[]> = {
  breaking: [],
  feat: [],
  fix: [],
  other: [],
}

for (const c of commits) {
  const cat = categorise(c.subject, c.body)
  grouped[cat].push(c)
}

if (isJson) {
  console.log(JSON.stringify({ tag, commits: commits.length, grouped }, null, 2))
  process.exit(0)
}

// ── Markdown output ────────────────────────────────────────────────

if (tag) {
  console.log(`## What's changed since ${tag}\n`)
} else {
  console.log("## What's changed\n")
}

if (grouped.breaking.length > 0) {
  console.log("### ⚠️ BREAKING CHANGES\n")
  for (const c of grouped.breaking) {
    const short = c.hash.slice(0, shortHashLen)
    console.log(
      `- ${stripType(c.subject)} ([${short}](https://github.com/crvouga/mockingbird/commit/${c.hash}))`,
    )
    if (c.body && /^BREAKING(\s+CHANGE)?:\s*(.+)$/m.test(c.body)) {
      const detail = c.body.replace(/^BREAKING(\s+CHANGE)?:\s*/, "").trim()
      if (detail) console.log(`  ${detail}`)
    }
  }
  console.log("")
}

if (grouped.feat.length > 0) {
  console.log("### 🚀 Features\n")
  for (const c of grouped.feat) {
    const short = c.hash.slice(0, shortHashLen)
    console.log(
      `- ${stripType(c.subject)} ([${short}](https://github.com/crvouga/mockingbird/commit/${c.hash}))`,
    )
  }
  console.log("")
}

if (grouped.fix.length > 0) {
  console.log("### 🐛 Bug Fixes\n")
  for (const c of grouped.fix) {
    const short = c.hash.slice(0, shortHashLen)
    console.log(
      `- ${stripType(c.subject)} ([${short}](https://github.com/crvouga/mockingbird/commit/${c.hash}))`,
    )
  }
  console.log("")
}

if (grouped.other.length > 0) {
  console.log("### 📦 Other Changes\n")
  for (const c of grouped.other.slice(0, 10)) {
    const short = c.hash.slice(0, shortHashLen)
    console.log(
      `- ${stripType(c.subject) || c.subject} ([${short}](https://github.com/crvouga/mockingbird/commit/${c.hash}))`,
    )
  }
  if (grouped.other.length > 10) {
    console.log(`- _...and ${grouped.other.length - 10} more_`)
  }
  console.log("")
}

console.log("---\n")
console.log(
  `_Generated by [release-notes.ts](https://github.com/crvouga/mockingbird/blob/main/scripts/release-notes.ts)_`,
)
